### PR TITLE
Refactor reborn eligibility

### PR DESCRIPTION
**Pull request by ikacnep**

### CODE REVIEW

**Comment by igroglaz** [comment]
cool, but it will be fun to format it with comment to make easier maintaining

uint32_t min_gold_regular[] = {
0, // server 1
0, // server 2
30000, // server 3
200000, // server 4
....

**Comment by igroglaz** [comment]
also atm
    if (srvid == 2 && chr.Money < 30000) {
                        meets_reborn_criteria = false;
                    }
                    else if (srvid == 3 && chr.Money < 200000) {
                        meets_reborn_criteria = false;
                        
we can see right on that it's receiving character from certain server. in refactored code it's not seen - so we must make emphasis on it in comments so after years maintainers will be able to understand what happening

**Comment by ikacnep** [comment]
> cool, but it will be fun to format it with comment to make easier maintaining
> 
> uint32_t min_gold_regular[] = { 0, // server 1 0, // server 2 30000, // server 3 200000, // server 4 ....

Done.

> we can see right on that it's !receiving character from certain server!. in refactored code it's not seen - so we must make emphasis on it in comments so after years maintainers will be able to understand what happening

We have a comment right above, on line 957 --- `we check there _!from which server!_ we received character`. Isn't it enough?

**Comment by igroglaz** [comment]
not enough imho. we must give emphasis on it, remind. cause it's not obvious and after year when dev return to the code - he might have troubles to understand whats going on

**Pull request merged**
